### PR TITLE
breaking: Renaming pkg to dts (fixes #14)

### LINKED ISSUE #14: Publishing fork under a new name
First let me thank you for your amazing work on this fork.

It would be nice that all of this effort gets more recognition. It's actually not that straightforward to land on this repository.

Have you considered publishing this package under a new name?

Regards,

### PR DESCRIPTION
**Pull request by aladdin-add**
todos:
 
- [x]    1. update readme 8539dd0a7983a1639c4af924010cb2b052793c01
- [x]  2. contributing guide d07b9fa33c4dd6b578821d11ec0e7d0188a35937
- [x]   3. lib template readme 12ffbdfb6cde24f51f030d5235a0f97201888b14
- [x] 4. issue/PR templates e37b3450c760999c9ace4a8a6b8172cb2e9eab3c
- [ ]   5. add website

### CODE REVIEW

**Comment by aladdin-add** [comment]
just released a prerelease: https://www.npmjs.com/package/dts-cli/v/0.17.0-0

**Comment by sidwebworks** [comment]
Cool as soon as I get time I will finish up the docs, also I think we can re-use the site? what do you think? @aladdin-add  it's built on next, tailwind, and mdx.

**Comment by aladdin-add** [comment]
👍

**Comment by aladdin-add** [comment]
I'm going to merge it; the to-dos can be done in following PRs.

**Pull request merged**
